MYSQL_USERNAME = root
MYSQL_PASSWORD = 
MYSQL_DATABASE = test

GIT_REVISION = master

MINIMIZE_CSS = false
MINIMIZE_JS = false

INSTAGRAM_CLIENT_ID =
INSTAGRAM_CLIENT_SECRET =

FACEBOOK_CLIENT_ID =
FACEBOOK_CLIENT_SECRET =

TWITTER_CONSUMER_KEY =
TWITTER_CONSUMER_SECRET =